version: '3.4'

services:
  pw_app:
    image: pw_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DB_HOSTNAME=postgres
      - DB_USER=postgres
      - DB_PORT=5432 
      - DB_DATABASE=PW
      - REDIS_KEY_PREFIX=sloboda
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_DECODE_RESPONSES=True
      - REGIOJET_BASE_URL=https://brn-ybus-pubapi.sa.cz/restapi/routes/search/simple
      - REGIOJET_LOCATIONS_URL=https://brn-ybus-pubapi.sa.cz/restapi/consts/locations 
      - REGIOJET_CURRENCY_RATES=https://api.skypicker.com/rates
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=PW
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis: 
    image: redis
    restart: always
    command: redis-server  --requirepass password

volumes:
  postgres-db:


